# Generated by Django 3.1.6 on 2021-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calciatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('ruolo', models.CharField(choices=[('P', 'portiere'), ('D', 'difensore'), ('C', 'centrocampista'), ('A', 'attaccante')], max_length=1)),
                ('squadra', models.CharField(max_length=256)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'svincolato'), (1, 'con_contratto')], default=0)),
            ],
            options={
                'verbose_name': 'calciatori',
                'verbose_name_plural': 'calciatori',
            },
        ),
    ]
